services:
  - type: web
    name: shared-alarm-socket
    env: node
    rootDir: socket-server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    plan: free
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
